import { Injectable, NotFoundException } from '@nestjs/common';
import { Ticket } from './ticket.interface.js';
import { CreateTicketDto } from './dto/create-ticket.dto.js';

@Injectable()
export class TicketsService {
  private readonly tickets: Ticket[] = [
    {
      id: 1,
      subject: 'Unable to reset password',
      description:
        "I requested a password reset but haven't received the reset email. I have checked my spam and junk folders as well.",
      priority: 'high',
      status: 'open',
      createdAt: '2026-09-19T10:30:00Z',
    },
    {
      id: 2,
      subject: 'Payment failed during checkout',
      description:
        'My card payment failed while trying to complete an order. The amount was temporarily deducted from my account.',
      priority: 'high',
      status: 'open',
      createdAt: '2026-09-18T14:45:00Z',
    },
    {
      id: 3,
      subject: 'Dashboard loading slowly',
      description:
        'The dashboard takes more than 10 seconds to load, especially when viewing a large number of records.',
      priority: 'medium',
      status: 'open',
      createdAt: '2026-09-17T09:15:00Z',
    },
    {
      id: 4,
      subject: 'Update account email address',
      description:
        'I would like to change the email address associated with my account.',
      priority: 'low',
      status: 'closed',
      createdAt: '2026-09-16T16:20:00Z',
    },
    {
      id: 5,
      subject: 'Two-factor authentication not working',
      description:
        'The verification code generated by my authenticator app is being rejected even though the device time is synchronized.',
      priority: 'high',
      status: 'open',
      createdAt: '2026-09-16T11:05:00Z',
    },
    {
      id: 6,
      subject: 'Incorrect invoice amount',
      description:
        'The amount shown on my latest invoice does not match the subscription price shown in my account.',
      priority: 'medium',
      status: 'closed',
      createdAt: '2026-09-15T13:40:00Z',
    },
    {
      id: 7,
      subject: 'How can I export my data?',
      description:
        'I need to download my account data for backup purposes. Where can I find the export option?',
      priority: 'low',
      status: 'closed',
      createdAt: '2026-09-14T08:50:00Z',
    },
    {
      id: 8,
      subject: 'File upload keeps failing',
      description:
        'I am trying to upload a PDF document, but the upload fails after reaching approximately 80 percent.',
      priority: 'medium',
      status: 'open',
      createdAt: '2026-09-13T17:25:00Z',
    },
    {
      id: 9,
      subject: 'Account temporarily locked',
      description:
        'My account was locked after several unsuccessful login attempts. I am unable to access my dashboard.',
      priority: 'high',
      status: 'closed',
      createdAt: '2026-09-12T12:10:00Z',
    },
    {
      id: 10,
      subject: 'Notification preferences',
      description:
        'I would like to stop receiving promotional emails while keeping important account notifications enabled.',
      priority: 'low',
      status: 'open',
      createdAt: '2026-09-11T15:35:00Z',
    },
    {
      id: 11,
      subject: 'Mobile application crashes',
      description:
        'The mobile application closes unexpectedly whenever I try to open the notifications section.',
      priority: 'high',
      status: 'open',
      createdAt: '2026-09-10T19:05:00Z',
    },
    {
      id: 12,
      subject: 'Unable to update profile picture',
      description:
        'The profile picture upload appears to complete successfully, but the old image is still displayed.',
      priority: 'low',
      status: 'closed',
      createdAt: '2026-09-09T10:45:00Z',
    },
  ];

  private nextTicketId=13;
  findAll(status?:Ticket['status'], priority?:Ticket['priority']) {
    let tickets = this.tickets
    if(status){
      tickets = tickets.filter((ticket)=>ticket.status===status)
    }
    if(priority){
      tickets = tickets.filter((ticket)=>ticket.priority===priority)
    }
    return tickets
  }
  findOne(id: number) {
    const ticket =  this.tickets.find((ticket) => ticket.id === id);
    if(!ticket){
      throw new NotFoundException(`Ticket with id ${id} not found`)
    }
    return ticket
  }
  create(createTicketDto:CreateTicketDto){
    const ticket:Ticket={
      id:this.nextTicketId++,
      subject:createTicketDto.subject,
      description:createTicketDto.description,
      priority:createTicketDto.priority,
      status:'open',
      createdAt:new Date().toISOString()

    }
    this.tickets.push(ticket)
    return ticket
  }
}
